[project]
name = "mcp-http-validator"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
test = "pytest"
lint = "ruff check ."
dev = "python -m mcp_http_validator.cli"

[dependencies]
python = ">=3.11"
pip = "*"
httpx = ">=0.27.0"
pydantic = ">=2.0"
authlib = ">=1.3.0"
rich = ">=13.0"
click = ">=8.1"
python-dotenv = ">=1.0"
pyjwt = ">=2.8"
cryptography = ">=42.0"
pytest = ">=8.0"
pytest-asyncio = ">=0.23"

[pypi-dependencies]
mcp-http-validator = { path = ".", editable = true }