[project]
name = "acme-certmanager"
channels = ["conda-forge", "pypi"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
python = ">=3.10,<3.13"
pip = "*"

[pypi-dependencies]
fastapi = ">=0.104.1"
hypercorn = ">=0.14.0"
acme = ">=2.8.0"
josepy = ">=1.14.0"
cryptography = ">=41.0.7"
redis = { version = ">=5.0.1", extras = ["hiredis"] }
apscheduler = ">=3.10.4"
pydantic = ">=2.5.0"
python-multipart = ">=0.0.6"
httpx = ">=0.25.2"
pytest = ">=7.4.3"
pytest-asyncio = ">=0.21.1"
pytest-timeout = ">=2.2.0"
jupyter-book = ">=0.15.1"
setuptools = ">=68.0.0"
wheel = ">=0.41.0"
build = ">=1.0.3"
twine = ">=4.0.2"
ruff = ">=0.1.6"
requests = ">=2.31.0"
tabulate = ">=0.9.0"
websockets = ">=11.0"
mcp-streamablehttp-client = { path = "./mcp-streamablehttp-client", editable = true }
mcp-echo-streamablehttp-server-stateful = { path = "./mcp-echo-streamablehttp-server-stateful", editable = true }
mcp-echo-streamablehttp-server-stateless = { path = "./mcp-echo-streamablehttp-server-stateless", editable = true }

[tasks]
test = "pytest tests/ -v"
test-all = "pytest tests/ -v --tb=short"
test-verbose = "pytest tests/ -vvv"
lint = "ruff check . && ruff format ."
dev = "hypercorn acme_certmanager.server:app --reload --bind 0.0.0.0:8000"
docs-build = "jupyter-book build docs"