#!/bin/bash
# Demonstration of enhanced OAuth workflow logs

echo "=== Enhanced OAuth Workflow Logs Example ==="
echo ""
echo "With the enhancements, the logs now show:"
echo ""
echo "1. Authorization Request with Referer:"
echo "   2025-08-02 16:45:00Z [INFO] auth.atradev.org 213.47.196.26 - GET /authorize [OAuth:authorize] q=client_id=client_Ebb8g95l9shqpxykc0pmBg redirect_uri=https%3A%2F%2Fclaude.ai%2Fapi%2Fmcp%2Fauth_call state=K2nt_soXbY7e1HNuBZBYBwp_8tnfYSxrhBK2c5V2ohA scope=openid+profile+email+mcp%3Aread+mcp%3Awrite referer=https://claude.ai/settings/mcp UA=\"Mozilla/5.0\""
echo ""
echo "2. Authorization Redirect Response (shows WHERE it's redirecting):"
echo "   2025-08-02 16:45:00Z [INFO] auth.atradev.org 213.47.196.26 -> 307 (7.5ms) redirect_to=https://github.com/login/oauth/authorize auth=pending_github_auth"
echo ""
echo "3. Callback Request with Authorization Code:"
echo "   2025-08-02 16:45:10Z [INFO] auth.atradev.org 213.47.196.26 - GET /callback [OAuth:callback state=K2nt_soXbY7e1HNuBZBYBwp_8tnfYSxrhBK2c5V2ohA] q=code=abc123def456 state=K2nt_soXbY7e1HNuBZBYBwp_8tnfYSxrhBK2c5V2ohA referer=https://github.com/ UA=\"Mozilla/5.0\""
echo ""
echo "4. Callback Redirect Response (shows final redirect to Claude.ai):"
echo "   2025-08-02 16:45:10Z [INFO] auth.atradev.org 213.47.196.26 -> 307 (125.5ms) redirect_to=https://claude.ai/api/mcp/auth_callback auth=success github_user=atrawog"
echo ""
echo "=== Key Enhancements ==="
echo ""
echo "Request lines now show:"
echo "- Referer header: Shows where the request came from"
echo "- OAuth state and action details"
echo "- Query parameters parsed for OAuth fields"
echo ""
echo "Response lines now show:"
echo "- redirect_to: The actual destination of 307 redirects"
echo "- auth: Authorization status (pending_github_auth, success, failed)"
echo "- github_user: Username after successful GitHub authentication"
echo ""
echo "=== OAuth Flow Summary ==="
echo "1. User clicks 'Connect' in Claude.ai (referer=https://claude.ai/settings/mcp)"
echo "2. Redirected to auth.atradev.org/authorize"
echo "3. Redirected to GitHub (redirect_to=https://github.com/login/oauth/authorize)"
echo "4. User authorizes on GitHub"
echo "5. GitHub redirects back to callback (referer=https://github.com/)"
echo "6. Callback processes and redirects to Claude.ai (redirect_to=https://claude.ai/api/mcp/auth_callback)"
echo ""
echo "The enhanced logging provides complete visibility into the OAuth flow!"