# Book settings
title: ACME Certificate Manager Documentation
author: ACME CertManager Team
logo: ""

# Force re-execution of notebooks on each build
execute:
  execute_notebooks: 'off'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/acme-certmanager/acme-certmanager
  path_to_book: docs
  branch: main

# Add GitHub buttons to your book
html:
  use_issues_button: true
  use_repository_button: true

# Parse and render settings
parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

# Define the table of contents
sphinx:
  config:
    html_theme: sphinx_book_theme
    html_theme_options:
      repository_url: https://github.com/acme-certmanager/acme-certmanager
      use_repository_button: true
      use_issues_button: true
      use_edit_page_button: true
      path_to_docs: docs
      branch: main
    language: en